export default Object.freeze({
  HOME: "Home",

  AUTH_MAIN: "Auth Main",
  AUTH_LOGIN: "Login",
  AUTH_HELP: "Help",
  AUTH_FORGOT: "Forgot Password",
  AUTH_PHONENUMBER: "SignUp Phonenumber",
  AUTH_OTP: "SignUp OTP",
  AUTH_SET_PASSWORD: "SignUp Password",

  ACCOUNTS_MAIN: "Me",
  ACCOUNTS_SETTINGS: "Account Settings",
  ACCOUNTS_EDT_PRFL: "Edit Profile",
  ACCOUNTS_ADDRESS: "My Address",
  ACCOUNTS_NEW_ADDRESS: "New Address",
  ACCOUNTS_SOCIAL_MEDIA: "Social Media Accounts",
  ACCOUNTS_DELETE: "Delete Account",
  ACCOUNTS_LOGOUT: "Logout",

  SHOP_MAIN: "Shop Main",
  SHOP_SETTINGS: "Shop Settings",
  SHOP_CHAT: "Shop Chat",
  SHOP_PRODUCTS: "Shop Products",
  SHOP_PRODUCT_DETAILS: "Shop Product Details",
  SHOP_SHIP: "Shop Ship",
  SHOP_CANCELLED: "Shop Cancelled",
  SHOP_RETURNS: "Shop Returns",
  SHOP_MARKETING: "Shop Marketing",
  SHOP_FINANCE: "Shop Finance",
  SHOP_REPORTS: "Shop Reports",
  SHOP_ADDRESS: "Shop Address",
  SHOP_EDIT_ADDRESS: "Shop Edit Address",
  SHOP_PAYMENT: "Shop Payment",

  SEARCH_MY_PRODUCT: "Search My Product",
  PRODUCT_ADD: "Add Product",
  ADD_VARIATION: "Add Variation",
  ADD_WHOLESALE: "Add Wholesale",
  SET_STOCK_PRICE: "Set Stock and Price",
  SHIPPING_DETAILS: "Shipping Details",
  CHOOSE_CATEGORY: "Choose Category",

  MY_BASKET: "My Basket",
  CHECKOUT: "Checkout",
  NOTIFICATIONS: "Notifications",
  ORDER_FULLFILLMENT: "Orders",
  TRACKER: "Tracker",
});
