export default Object.freeze({
  HOME: "Home",

  AUTH_MAIN: "Auth Main",
  AUTH_LOGIN: "Login",
  AUTH_HELP: "Help",
  AUTH_FORGOT: "Forgot Password",

  ACCOUNTS_MAIN: "User Account Main",
  ACCOUNTS_SETTINGS: "Account Settings",
  ACCOUNTS_EDT_PRFL: "Edit Profile",
  ACCOUNTS_ADDRESS: "My Address",
  ACCOUNTS_NEW_ADDRESS: "New Address",
  ACCOUNTS_SOCIAL_MEDIA: "Social Media Accounts",
  ACCOUNTS_DELETE: "Delete Account",
  ACCOUNTS_LOGOUT: "Logout",

  SHOP_MAIN: "Shop Main",

  DUMMY_ABOUT: "About",
  DUMMY_FAQ: "FAQ",
  DUMMY_FRIEND_REFER: "Friend Refer",
  DUMMY_HELP_CENTRE: "Help Centre",
  DUMMY_KAROSA_WALLET: "Karosa Wallet",
  DUMMY_MESSAGES: "Messages",
  DUMMY_PRIVACY_POLICY: "Privacy Policy",
  DUMMY_PURCHASES: "Purchases",
  DUMMY_TO_PAY: "To Pay",
  DUMMY_TO_RATE: "To Rate",
  DUMMY_TO_RECEIVE: "To Receive",
  DUMMY_TO_SHIP: "To Ship",
  DUMMY_VOUCHERS: "Vouchers",
  DUMMY_WISHLIST: "Wishlist",
  DUMMY_CANCELLED: "Cancelled",
  DUMMY_FINANCE: "Finance",
  DUMMY_PRODUCTS: "Products",
  DUMMY_REPORTS: "Reports",
  DUMMY_RETURNS: "Returns",
  DUMMY_MARKETING: "Marketing",
  DUMMY_SALES: "Sales",
});
