/**
 *
 * @format
 *
 */

import { WishlistProd } from "@app/redux/api-models/wishlist";
import { WishlistCategories } from "@app/redux/api-models/wishlist-categories";

export const mockProducts: WishlistProd[] = [
  {
    id: 1,
    name: "Banana",
    categoryId: 1,
    description: "mock description",
    shopId: 2,
    orgnlPrice: "500",
    dsctdPrice: "300",
    rating: 5,
    createdAt: "",
    updatedAt: "",
    discount: 30,
    stocks: 50,
  },
  {
    id: 2,
    name: "Apple",
    categoryId: 1,
    description: "mock description",
    shopId: 2,
    orgnlPrice: "400",
    dsctdPrice: "200",
    rating: 4,
    createdAt: "",
    updatedAt: "",
    discount: 50,
    stocks: 0,
  },
  {
    id: 3,
    name: "Mango",
    categoryId: 1,
    description: "mock description",
    shopId: 2,
    orgnlPrice: "100",
    dsctdPrice: "50",
    rating: 4,
    createdAt: "",
    updatedAt: "",
    discount: 20,
    stocks: 0,
  },
  {
    id: 4,
    name: "Okra",
    categoryId: 2,
    description: "mock description",
    shopId: 2,
    orgnlPrice: "200",
    dsctdPrice: "150",
    rating: 3,
    createdAt: "",
    updatedAt: "",
    discount: 10,
    stocks: 0,
  },
  {
    id: 5,
    name: "Kape Barako",
    categoryId: 3,
    description: "mock description",
    shopId: 2,
    orgnlPrice: "200",
    dsctdPrice: "150",
    rating: 3,
    createdAt: "",
    updatedAt: "",
    discount: 10,
    stocks: 0,
  },
  {
    id: 6,
    name: "Pears",
    categoryId: 4,
    description: "mock description",
    shopId: 2,
    orgnlPrice: "200",
    dsctdPrice: "150",
    rating: 3,
    createdAt: "",
    updatedAt: "",
    discount: 10,
    stocks: 1,
  },
];

export const categories: WishlistCategories[] = [
  { id: 1, name: "Fruits", code: "fruits" },
  { id: 2, name: "Vegetables", code: "vegetables" },
  { id: 3, name: "Coffee", code: "coffee" },
  { id: 4, name: "Root Crops", code: "root_crops" },
  { id: 5, name: "Sea Foods & Meat", code: "meat" },
  { id: 6, name: "Herbs & Spices", code: "spices" },
  { id: 7, name: "Grains", code: "grains" },
  { id: 8, name: "Seeds & Seedlings", code: "seedling" },
  { id: 9, name: "Syrups & Beverages", code: "syrup" },
  { id: 10, name: "Flowers", code: "flower" },
  { id: 11, name: "Cheese", code: "cheese" },
  { id: 12, name: "Grains", code: "grains" },
];
