/**
 *
 * @format
 *
 */

import { WishlistProd } from "@app/redux/api-models/wishlist";
import { WishlistCategories } from "@app/redux/api-models/wishlist-categories";
import { WishlistDiscount } from "@app/redux/api-models/wishlist-discount";

export const mockProducts: WishlistProd[] = [
  {
    id: 1,
    name: "Banana",
    categoryId: 1,
    description: "mock description",
    shopId: 2,
    orgnlPrice: "500",
    dsctdPrice: "300",
    rating: 5,
    createdAt: "",
    updatedAt: "",
    discount: 30,
    stocks: 20,
  },
  {
    id: 2,
    name: "Apple",
    categoryId: 1,
    description: "mock description",
    shopId: 2,
    orgnlPrice: "400",
    dsctdPrice: "200",
    rating: 4,
    createdAt: "",
    updatedAt: "",
    discount: 10,
    stocks: 0,
  },
  {
    id: 3,
    name: "Mango",
    categoryId: 1,
    description: "mock description",
    shopId: 2,
    orgnlPrice: "100",
    dsctdPrice: "50",
    rating: 4,
    createdAt: "",
    updatedAt: "",
    discount: 50,
    stocks: 0,
  },
  {
    id: 4,
    name: "Okra",
    categoryId: 2,
    description: "mock description",
    shopId: 2,
    orgnlPrice: "200",
    dsctdPrice: "150",
    rating: 3,
    createdAt: "",
    updatedAt: "",
    discount: 30,
    stocks: 0,
  },
  {
    id: 5,
    name: "Kape Barako",
    categoryId: 3,
    description: "mock description",
    shopId: 2,
    orgnlPrice: "200",
    dsctdPrice: "150",
    rating: 3,
    createdAt: "",
    updatedAt: "",
    discount: 5,
    stocks: 0,
  },
  {
    id: 6,
    name: "Pears",
    categoryId: 4,
    description: "mock description",
    shopId: 2,
    orgnlPrice: "200",
    dsctdPrice: "150",
    rating: 3,
    createdAt: "",
    updatedAt: "",
    discount: 10,
    stocks: 1,
  },
];

export const categories: WishlistCategories[] = [
  { id: 1, name: "Fruits", code: "fruits" },
  { id: 2, name: "Vegetables", code: "vegetables" },
  { id: 3, name: "Coffee", code: "coffee" },
  { id: 4, name: "Root Crops", code: "root_crops" },
  { id: 5, name: "Sea Foods & Meat", code: "meat" },
  { id: 6, name: "Herbs & Spices", code: "spices" },
  { id: 7, name: "Grains", code: "grains" },
  { id: 8, name: "Seeds & Seedlings", code: "seedling" },
  { id: 9, name: "Syrups & Beverages", code: "syrup" },
  { id: 10, name: "Flowers", code: "flower" },
  { id: 11, name: "Cheese", code: "cheese" },
  { id: 12, name: "Grains", code: "grains" },
];
export const discounts: WishlistDiscount[] = [
  { id: 5, discount: "5%" },
  { id: 10, discount: "10%" },
  { id: 15, discount: "15%" },
  { id: 20, discount: "20%" },
  { id: 25, discount: "25%" },
  { id: 30, discount: "30%" },
  { id: 35, discount: "35%" },
  { id: 40, discount: "40%" },
  { id: 45, discount: "45%" },
  { id: 50, discount: "50%" },
  { id: 55, discount: "55%" },
  { id: 60, discount: "60%" },
  { id: 65, discount: "65%" },
  { id: 70, discount: "70%" },
  { id: 75, discount: "75%" },
  { id: 80, discount: "80%" },
  { id: 85, discount: "85%" },
  { id: 90, discount: "90%" },
  { id: 95, discount: "95%" },
  { id: 100, discount: "100%" },
];
